###############################################################
#
#  These vars are defiNed for each beamline/server installation
#
################################################################

deployment_dir: /opt/epicsTest
AD_modules_local:
      - ADPilatus
      - ADEiger
      - ADPointGrey
      - ADProsilica 
      - xspress3

_AD_modules_local:
    ADPilatus:
        version: R2-8
    ADEiger:
        version: master
    ADPointGrey:
        version: master
    ADProsilica:
        version: master 

_AD_satellites: 
    xspress3:
        version: master

##############################
#
# END of local vars section
#
###############################
proxy_https:
      https_proxy: https://proxy:8888

proxy_http:
      http_proxy: http://proxy:8888

epics_base_version: R7.0.3.1
#synApps_version: R6-1
synApps_version: master
# sequencer is not a git project it should be wget
#sequencer:
#    version: 2.2.8  

synApps_modules: 
      - configure
      - documentation
      - utils

epics_modules: 
      - ipac
      - asyn
      - autosave 
      - busy
      - sscan
      - calc
      - iocStats
# We need to have a list and an array 
# to be able to loop over two variables in the git module
_epics_modules:
  ipac: 
#    version: 2.15
    version: master
    name: IPAC
  asyn:
  # version OK
    version: R4-37
    name: ASYN
  autosave:
  # version OK
    version: R5-10
    name: AUTOSAVE  
  busy:
  # version OK
    version: R1-7-2
    name: BUSY
  sscan:
  # version OK
    version: R2-11-3
    name: SSCAN
  calc:
  # version OK
    version: R3-7-3
    name: CALC
  iocStats:
  #  version: 3.1.16
    version: master
    name: DEVIOCSTATS 
  seq:
    version: 2.2.8
    name: SNCSEQ  

# Order of AD_modules is very important, they will be compiled  in this order
AD_modules:
      - ADSupport
      - ADCore
      - ADSimDetector
#      - ADPilatus
#      - ADEiger
#      - ADPointGrey
areaDetector:
  areaDetector:
    version: master
  ADSupport:
    version: R1-9
    name: ADSUPPORT
  ADCore: 
    version: R3-8
    name: ADCORE
  ADSimDetector:
    version: master  
    name: ADSIMDETECTOR
  ADPilatus: 
    version: R2-8
    name: ADPILATUS
  ADEiger:
    version: master
    name: ADEIGER
  ADPointGrey:  
    version: master
    name: ADPOINTGREY

  
        