- include_tasks: "{{ ansible_os_family }}.yml"

- name: clone ADEiger
  git: 
        clone: yes
        update: yes
        force: yes
        dest: "{{deployment_dir}}/support/areaDetector/ADEiger"
        repo: "https://github.com/areaDetector/ADEiger"
        version: "{{_AD_modules_local.ADEiger.version }}"
  environment: "{{ proxy_https }}" 

- name: build ADEiger
  command: 
  args: 
        cmd: make -sj
        chdir: "{{deployment_dir}}/support/areaDetector/ADEiger"
