
- name: clone ADProsilica
  git: 
        clone: yes
        update: yes
        force: yes
        dest: "{{deployment_dir}}/support/areaDetector/ADProsilica"
        repo: "https://github.com/areaDetector/ADProsilica"
        version: "{{_AD_modules_local.ADProsilica.version }}"
  environment: "{{ proxy_https }}" 

- name: build ADProsilica
  command: 
  args: 
        cmd: make -sj
        chdir: "{{deployment_dir}}/support/areaDetector/ADProsilica"
